import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { Inter } from "next/font/google";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dominick DeVincenzo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.variable} font-sans antialiased`}>
        <div className="min-h-screen px-6 sm:px-12 md:px-24 lg:px-32 xl:px-48 2xl:px-72 py-15">
          <div className="mx-auto w-full max-w-3xl">{children}</div>
        </div>
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
